---
abstract: 'call object methods in array context and return it as arrayref'
author:
  - 'Tomohiro Hosaka <bokutin@bokut.in>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Plugin-ArrayRef
no_index:
  directory:
    - inc
    - t
requires:
  Template: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bokutin/Template-Plugin-ArrayRef.git
version: 0.1
